---
- name: Configurar VPS para microservicios con Docker
  hosts: vps
  become: yes
  vars_files:
    - group_vars/vps.yml  # Opcional si el grupo se llama igual

  tasks:

    - name: Instalar dependencias
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - docker.io
        - git
        - ufw

    - name: Iniciar Docker al arrancar
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Crear red Docker para microservicios
      shell: docker network create app-tier || true

    - name: Iniciar sesión en DockerHub
      shell: echo "{{ docker_pass }}" | docker login -u "{{ docker_user }}" --password-stdin

    - name: Lanzar servicio 1
      shell: |
        docker rm -f servicio1 || true
        docker run -d --name servicio1 \
          --network app-tier \
          -p 8000:8000 \
          turegistry/servicio1:latest

    - name: Lanzar servicio 2
      shell: |
        docker rm -f servicio2 || true
        docker run -d --name servicio2 \
          --network app-tier \
          -p 8001:8000 \
          turegistry/servicio2:latest

    - name: Lanzar Watchtower
      shell: |
        docker rm -f watchtower || true
        docker run -d --name watchtower \
          --restart always \
          -v /var/run/docker.sock:/var/run/docker.sock \
          containrrr/watchtower \
          --cleanup --interval 30
